name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le build à chaque push sur la branche main

permissions:
  contents: write # Autorise l'action à créer la branche gh-pages et à y pousser du code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Version récente de Node
          cache: 'npm'       # Accélère les prochains builds en mettant en cache les modules

      - name: Install dependencies 🔧
        run: npm install

      - name: Build project 🏗️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Le dossier que Vue génère (souvent 'dist')
          branch: gh-pages # La branche de destination pour l'hébergement
