name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Le déploiement se déclenche quand on push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Le dossier généré par Vue
          branch: gh-pages # La branche où le site compilé sera envoyé
